name: BRS Commit Checker Report
on:
      workflow_dispatch:
        inputs:
            fix_version:
                type: string
                required: true
                description: The ICU Jira "Fix Version" semver
            from_git_ref:
                type: string
                required: true
                description: The git ref start of comparison range. Prefix branches with `origin/`.
            end_git_ref:
                type: string
                required: true
                description: The git ref end of comparison range. Must be descendant of `from_git_ref`. Prefix branches with `origin/`.
            # Jira user name & API token is used for processing sensitive tickets
            jira_user_email:
                type: string
                required: false
                description: (optional to include sensitive tickets) Email address of Jira user
            # Jira user name & API token is used for processing sensitive tickets
            # We protect the API token as a secret by preventing its value from pasted at the command line
            # by using add-mask to obfuscate secret values in the jobs
            # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
            jira_user_api_token:
                type: string
                required: false
                description: (optional to include sensitive tickets) API token of Jira user

jobs:
    commit-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-tags: true
                fetch-depth: 0
            # workaround for bug in checkout action. this step should be redundant.
            # https://github.com/actions/checkout/issues/1471
            # https://github.com/actions/checkout/issues/1781
            # https://github.com/actions/checkout/issues/701#issuecomment-1133937950
            - name: Fetch all tags
              run: |
                git fetch --tags origin
            - name: Fetch all branches
              run: |
                git fetch origin
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.8'
                cache: 'pipenv'
                cache-dependency-path: |
                    tools/commit-checker/Pipfile
                    tools/commit-checker/Pipfile.lock
            - name: Install pipenv
              run: |
                sudo pip3 install pipenv
              # Use add-mask to obfuscate secret values in the jobs
              # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
              # https://stackoverflow.com/a/71698374/2077918
            - name: Store Jira credentials if provided
              run: |
                JIRA_USERNAME=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.jira_user_email' )
                echo "::add-mask::${JIRA_USERNAME}"
                JIRA_PASSWORD=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.jira_user_api_token' )
                echo "::add-mask::${JIRA_PASSWORD}"
                if [ ! -z "${JIRA_USERNAME}" ] && [ ! -z "${JIRA_PASSWORD}" ]
                then
                    echo "::add-mask::${JIRA_USERNAME}"
                    echo "::add-mask::${JIRA_PASSWORD}"
                    pushd ./tools/commit-checker
                    echo "appending username and password to .env file"
                    echo "JIRA_USERNAME=${JIRA_USERNAME}" >> ./.env
                    echo "JIRA_PASSWORD=${JIRA_PASSWORD}" >> ./.env
                    popd
                else
                    echo "Either jira_user_email or jira_user_api_token is empty. Not storing credentials file to enable access to sensitive tickets."
                fi
            - name: Generate report
              run: |
                pushd ./tools/commit-checker
                pipenv install
                pipenv run python3 check.py \
                    --jira-query "project=ICU AND fixVersion=${{ inputs.fix_version }}" \
                    --rev-range "${{ inputs.from_git_ref }}..${{ inputs.end_git_ref }}" > REPORT.md
                popd
            # https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/
            - name: Reproduce report as workflow job summary
              run: |
                cat ./tools/commit-checker/REPORT.md >> $GITHUB_STEP_SUMMARY
                echo "View the Summary page of this GHA Workflow instance to view the rendered Markdown of this report."
